//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDD_HRVEntities : DbContext
    {
        public BDD_HRVEntities()
            : base("name=BDD_HRVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<CuidadClientes> CuidadClientes { get; set; }
        public virtual DbSet<ProvinciaClientes> ProvinciaClientes { get; set; }
        public virtual DbSet<CabeceraEquipos> CabeceraEquipos { get; set; }
        public virtual DbSet<DetalleEquipos> DetalleEquipos { get; set; }
    }
}
