//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesTrabajo
    {
        public int id_orden { get; set; }
        public int id_equipo { get; set; }
        public string orden_tipotrabajo { get; set; }
        public int orden_tecnico { get; set; }
        public string orden_problema { get; set; }
        public string orden_estado { get; set; }
        public string orden_notas { get; set; }
        public System.DateTime orden_fechainicio { get; set; }
        public System.DateTime orden_fechafin { get; set; }
        public string orden_auxvar { get; set; }
        public Nullable<int> orden_auxint { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
